baseURL = 'https://igormihajlov.com/'
languageCode = 'en-us'
title = 'Igor Mihajlov'
theme = 'terminal'
pagination.pagerSize = 5

[params]
    contentTypeName = 'home'
    showMenuItems = 4
    fullWidthTheme = false
    centerTheme = true

[languages]
    [languages.en]
        title = 'Igors personal website [WIP]'
        subtitle = ''
        keywords = ''
        copyright = ''
        menuMore = 'Show more'
        readMore = 'Read more'
        readOtherPosts = 'Read other posts'

    [languages.en.params.logo]
        logoText = 'IGOR MIHAJLOV'
        logoHomeLink = '/'

    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = 'home'
            name = 'Home'
            url = '/'
        [[languages.en.menu.main]]
            identifier = 'about'
            name = 'About'
            url = '/about'
        [[languages.en.menu.main]]
            identifier = 'projects'
            name = 'Projects'
            url = '/projects'
        [[languages.en.menu.main]]
            identifier = 'posts'
            name = 'Posts'
            url = '/posts'
 
